### PR TITLE
Update Retrofit to 2.0.0 stable version

### PR DESCRIPTION
**Pull request by egor-n**

### CODE REVIEW

**Comment by egor-n** [comment]
There seems to be a problem with new OkHttp:

```
Caused by: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.Platform$Android@51cdf7, sslSocketFactory is class com.judopay.api.TlsSslSocketFactory
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:187)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:60)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:718)
        at com.judopay.api.JudoApiServiceFactory.getOkHttpClient(JudoApiServiceFactory.java:73)
        at com.judopay.api.JudoApiServiceFactory.createRetrofit(JudoApiServiceFactory.java:58)
        at com.judopay.api.JudoApiServiceFactory.createApiService(JudoApiServiceFactory.java:50)
        at com.judopay.Judo.getApiService(Judo.java:78)
        at com.judopay.RegisterCardFragment.onCreate(RegisterCardFragment.java:23)
        at android.app.Fragment.performCreate(Fragment.java:2198)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
        at android.app.BackStackRecord.run(BackStackRecord.java:793)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
        at android.app.FragmentController.execPendingActions(FragmentController.java:325)
        at android.app.Activity.performStart(Activity.java:6267)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
```

**Comment by JamesGoodwin** [comment]
Thanks for the feedback @egor-n. Agree that the Retrofit library should be upgraded to the stable version.

Looks like the issue relates to using OkHttp with the SslSocketFactory we use to ensure TLS 1.2 is used, will investigate and let you know.

**Comment by JamesGoodwin** [comment]
Looks like it's a bug in the Retrofit 2.0.0 release:
https://github.com/square/okhttp/issues/2323

**Comment by JamesGoodwin** [comment]
@egor-n The issue relates to a bug in OkHttp where it tries to find a field in the SslSocketFactory using reflection. If you can rename the field "internalSSLSocketFactory" to "delegate" in TlsSslSocketFactory.java it will work and I can approve your pull request. Thanks!

**Comment by egor-n** [comment]
I have tried changing `internalSSLSocketFactory` to `delegate` [here](https://github.com/JudoPay/Judo-Android/blob/4cdd2e3d2101e7ad2845aec0fdd6bf7051c1fe64/judo-sdk/src/main/java/com/judopay/api/TlsSslSocketFactory.java#L15) as [suggested by Jesse](https://github.com/square/okhttp/issues/2323#issuecomment-195173415) and it seems to work fine. I have updated the pull request accordingly.

**Pull request merged**
